#!/usr/bin/python3
import sys
from subprocess import call


class LetsManage:

    def __init__(self):
        print()

        if len(sys.argv) < 2:
            self._help()
        else:
            cmd = sys.argv[1]

            if cmd == 'certificates':
                call(['docker', 'compose', 'exec', 'nginx', 'certbot', 'certificates'])

            elif cmd == 'delete':
                call(['docker', 'compose', 'exec', 'nginx', 'certbot', 'delete'])

            elif cmd == 'reset':
                call(['docker', 'compose', 'exec', 'nginx', 'rm', '-rf', '/certs'])
                call(['docker', 'compose', 'exec', 'nginx', 'certbot', 'deleteall'])

            elif cmd == 'renew':
                self.log(f'Iniciando renovação\n')
                call(['touch', './nginx/etc/_renew'])
                call(['docker', 'compose', 'restart', 'nginx'])

            else:
                self._help()

    def log(self, msg):
        TAG = '\033[1m[let\'s nginx]\033[m'
        print(f'{TAG} {msg}', flush=True)

    def _help(self):
        msg = 'Utilização:\n'
        msg += '  - lets create [nome] [dominios] [email]\n'
        msg += '  - lets renew\n'

        print(msg)
        sys.exit(1)

if __name__ == '__main__':
    LetsManage()

