#!/usr/bin/python3
import sys
from subprocess import call


class LetsManage:

    def __init__(self):
        print()

        try:
            nome = sys.argv[1]
            dominio = sys.argv[2]
            email = sys.argv[3]
        except:
            print('\nUtilização: lets-nginx [nome] [dominios] [email]\n')
            sys.exit(1)

        self.log(f'Iniciando requisição de certificado\n')
        with open('./nginx/etc/_request', 'w') as _f:
            _f.write(f'{nome}\n{dominio}\n{email}')

        call(['docker', 'compose', 'restart', 'nginx'])

    def log(self, msg):
        TAG = '\033[1m[let\'s nginx]\033[m'
        print(f'{TAG} {msg}', flush=True)


if __name__ == '__main__':
    LetsManage()











'''
NOME="$1"
DOMINIO="$2"
EMAIL="$3"

if [ "$NOME" == "" ] || [ "$DOMINIO" == "" ] || [ "$EMAIL" ==  "" ]; then
    echo -e '\nUtilização: gerar_certificado [nome] [dominio] [email]\n'
    exit 1
fi

echo ""
echo "======================================================================================"
echo " Iniciando geração do certificado HTTPS para $DOMINIO"
echo "======================================================================================"
echo ""

dir=$(pwd)/$(dirname $0)
echo $dir
exit

echo "$NOME" > $dir/etc/_letsnginx
echo "$DOMINIO" >> $dir/etc/_letsnginx
echo "$EMAIL" >> $dir/etc/_letsnginx

docker compose restart nginx

while [ -f $dir/__letsnginx ]; do
    echo 'Aguardando certbot...'
    sleep 1
done


SUCESSO=0

echo
echo 'Arquivo gerado: certs/'$NOME/fullchain.pem
echo 'Arquivo gerado: certs/'$NOME/privkey.pem

if [ -f $dir/../certs/$NOME/fullchain.pem ] && [ -f $dir/../certs/$NOME/privkey.pem ]; then
    SUCESSO=1
fi


if [ $SUCESSO == 1 ]; then
    echo ''
    echo '============================================'
    echo ' Certificado gerado com sucesso!'
    echo '============================================'
    echo ''
else
    echo 'Erro! O certificado não foi gerado. Mais informações no log.'
fi
'''
