#!/bin/bash

CONFIG_DIR=/etc/nginx/http.d

# http plano
cp /nginx_conf/default.conf $CONFIG_DIR

echo -e "\n"
echo "======================================================"
echo " Let's NGINX!"
echo "======================================================"
echo


# verificando se todos os certificados mencionados no https.conf realmente existem
echo '>>> Lendo configurações'
echo

EXISTE_CERT=1
cfg_certs=$(grep '/nginx/certificados/' /nginx_conf/https.conf \
    | grep -v '#' | sed 's/ssl_certificate\(_key\)\?//g' | sed 's/;//')

for cert in $cfg_certs; do
    msg="Certificado: $cert"
    if [ ! -f $cert ]; then
        EXISTE_CERT=0
	msg="[erro] $msg"
    else
	msg="[ OK ] $msg"
    fi
    echo $msg
done

echo

if [ $EXISTE_CERT == 1 ]; then
    echo '>>> Todos os certificados foram encontrados, habilitando HTTPS...'
    echo
    cp /nginx_conf/https.conf $CONFIG_DIR

else
    echo '>>> Um ou mais certificados não foram encontrados. O HTTPS vai ficar desligado.'
    echo

    if [ -f $CONFIG_DIR/https.conf ]; then
        rm $CONFIG_DIR/https.conf
    fi
fi


# geração pendente
if [ -f /nginx/etc/_letsnginx ]; then
    /nginx/etc/_gerador
    rm /nginx/etc/_letsnginx

else
    # nginx runs
    nginx -g 'daemon off;'
fi

