#!/bin/bash

NOME="$1"
DOMINIO="$2"
EMAIL="$3"

if [ "$NOME" == "" ] || [ "$DOMINIO" == "" ] || [ "$EMAIL" ==  "" ]; then
    echo -e '\nUtilização: gerar_certificado [nome] [dominio] [email]\n'
    exit 1
fi

echo ''
echo '============================================'
echo ' Iniciando geração do certificado HTTPS'
echo '============================================'
echo ''

dir=$(pwd)/$(dirname $0)

echo "$NOME" > $dir/__letsnginx
echo "$DOMINIO" >> $dir/__letsnginx
echo "$EMAIL" >> $dir/__letsnginx

docker-compose restart nginx


SUCESSO=0

echo 'verificando arquivo' $dir/../certs/$NOME/privkey.pem

if [ -f $dir/../certs/$NOME/privkey.pem ]; then
    SUCESSO=1
fi


if [ $SUCESSO == 1 ]; then
    echo ''
    echo '============================================'
    echo ' Certificado gerado com sucesso!'
    echo '============================================'
    echo ''
else
    echo 'Erro! O certificado não foi gerado. Mais informações no log.'
fi
